version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/data:/app/data
    environment:
      - SECRET_KEY=your-production-secret-key-here
      - ENVIRONMENT=production
      - ALLOWED_ORIGINS=http://localhost,http://localhost:80,https://yourdomain.com
      - SUPABASE_URL=https://your-project-ref.supabase.co
      - SUPABASE_ANON_KEY=your-supabase-anon-key
      - SUPABASE_SERVICE_ROLE_KEY=your-supabase-service-role-key
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: